### ISSUE TITLE
[Bug] After disabling the GPT 4 model, you can still use the GPT 4 model by manually entering a custom model

### ISSUE THREAD

**Issue by yunxilyf** [H0llyW00dzZ/ChatGPT-Next-Web#100]
**Describe the bug**

**To Reproduce**
After disabling the GPT 4 model, you can still use the GPT 4 model by manually entering a custom model

**Deployment**
 Vercel

**Desktop (please complete the following information):**
 - Browser

**Comment by yunxilyf** [comment]
> can you try by clicking this a link before I push to main branch ?
> 
> https://chat-gpt-next-web-git-gpt-4issue-h0llyw00dzz-s-team.vercel.app/?_vercel_share=Zmnk5CIYnrCTrUgrbwLGAy6TYCW93q6x

The above deployment link does not disable GPT4

**Comment by H0llyW00dzZ** [comment]
hold on let me redeploy

**Comment by H0llyW00dzZ** [comment]
@yunxilyf try now


https://chat-gpt-next-web-git-gpt-4issue-h0llyw00dzz-s-team.vercel.app/?_vercel_share=Zmnk5CIYnrCTrUgrbwLGAy6TYCW93q6x

**Comment by yunxilyf** [comment]
> @yunxilyf try now
> 
> https://chat-gpt-next-web-git-gpt-4issue-h0llyw00dzz-s-team.vercel.app/?_vercel_share=Zmnk5CIYnrCTrUgrbwLGAy6TYCW93q6x

![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/44936564/34d0ce11-2d61-4f5d-8154-53062a435ec1)
It doesn't work, but it's not an API problem

**Comment by H0llyW00dzZ** [comment]
> > @yunxilyf try now
> > https://chat-gpt-next-web-git-gpt-4issue-h0llyw00dzz-s-team.vercel.app/?_vercel_share=Zmnk5CIYnrCTrUgrbwLGAy6TYCW93q6x
> 
> ![image](https://user-images.githubusercontent.com/44936564/282729283-34d0ce11-2d61-4f5d-8154-53062a435ec1.png) It doesn't work, but it's not an API problem

that's error from your one api
screenshot the error via network
like this 

![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/17626300/cfcd90c6-97e7-4e20-8a70-2e7effa66e83)

**Comment by yunxilyf** [comment]
I found it. It was my problem. I did not delete the previous conversation records. Now it is possible. Even if I manually add the GPT 4 model, I cannot select it.
