### ISSUE TITLE
[Bug] The API log shows that there are other additional request consumption, but there was no such problem before.

### ISSUE THREAD

**Issue by yunxilyf** [H0llyW00dzZ/ChatGPT-Next-Web#102]
**Describe the bug**

**To Reproduce**
The API log shows that there are other additional request consumption, but there was no such problem before.

**Deployment**

-  Vercel

![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/44936564/183d28a4-aa93-4788-90ab-645a11be26be)

**Comment by H0llyW00dzZ** [comment]
that's text-moderation openai
nothing bug you can disable by untick this

![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/17626300/1ad6659a-4766-413b-b701-c1b32a8df2f3)
