### ISSUE TITLE
[Bug] 使用Azure OpenAI 的时候没有流模式显示输出内容

### ISSUE THREAD

**Issue by yunxilyf** [H0llyW00dzZ/ChatGPT-Next-Web#119]
**Describe the bug**

**To Reproduce**
使用Azure OpenAI 的时候没有流模式显示输出内容

**Deployment**
-  Vercel

**Comment by H0llyW00dzZ** [comment]
Sorry
I can't test/fix for azure openai
don't have access on it

**Comment by yunxilyf** [comment]
> Sorry I can't test/fix for azure openai don't have access on it

I can provide test api, you can add me qq: 2574379425

**Comment by H0llyW00dzZ** [comment]
streaming already fix Refactor ChatGPT LLMApi #120
