### ISSUE TITLE
[Bug] The "Local Data" interface does not display the quantity at the beginning of "Dialogue," "Mask," and "Prompt" sections.

### ISSUE THREAD

**Issue by MuCqq** [H0llyW00dzZ/ChatGPT-Next-Web#143]
**Describe the bug**
The "Local Data" interface does not display the quantity at the beginning of "Dialogue," "Mask," and "Prompt" sections.

**Expected behavior**
"Dialogue," "Mask," and "Prompt" sections include quantity display.

**Screenshots**
![1700703900992](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/133507172/7635e8f4-9688-4311-a24e-4eebe5e8a163)

**Deployment**
- [ ] Docker
- [ √ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by MuCqq** [comment]
Ah, I see, so this is a title.

**Comment by H0llyW00dzZ** [comment]
> Ah, I see, so this is a title.

yes magic typescript
