### ISSUE TITLE
[Feature]  Some suggestions

### ISSUE THREAD

**Issue by XZ1314XZ** [H0llyW00dzZ/ChatGPT-Next-Web#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

# Suggestions
1. Unnecessary addition of too many models can be avoided by keeping only the following. Refer to the official feature [Continuous model upgrades](https://platform.openai.com/docs/models/continuous-model-upgrades)
```sh
CUSTOM_MODELS=-all,+gpt-3.5-turbo,+gpt-3.5-turbo-16k,+gpt-4,+gpt-4-32k,+gpt-4-1106-preview,+gpt-4-vision-preview,+dall-e-3,+dall-e-3-beta-instruct-vision
```
2. Consider merging another repository to enhance plugin functionality (https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD)

**Comment by H0llyW00dzZ** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> # Suggestions
> 1. Unnecessary addition of too many models can be avoided by keeping only the following. Refer to the official feature [Continuous model upgrades](https://platform.openai.com/docs/models/continuous-model-upgrades)
> 
> ```shell
> CUSTOM_MODELS=-all,+gpt-3.5-turbo,+gpt-3.5-turbo-16k,+gpt-4,+gpt-4-32k,+gpt-4-1106-preview,+gpt-4-vision-preview,+dall-e-3,+dall-e-3-beta-instruct-vision
> ```
> 
> 2. Consider merging another repository to enhance plugin functionality (https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD)

My fork is only for edge runtime. Does the "enhance plugin functionality" work in an edge runtime environment?

**Comment by H0llyW00dzZ** [comment]
Also about other model
You can also disable the other model on your own in the environment settings, when you create a sub-fork of this repository. 
Because The other model is still a work in progress, and I haven't continued to focus on it yet (Currently doing stack in backend built in golang).
