### ISSUE TITLE
GPT-4 Vision Preview Cutting Off Result Message [Bug] 

### ISSUE THREAD

**Issue by senja24** [H0llyW00dzZ/ChatGPT-Next-Web#303]
### Bug Description

I'm writing to report a bug I've encountered while using the GPT-4 Vision Preview feature in the app. The feature is cutting off the result message, showing only a single line, and not displaying the full message.

### Steps to Reproduce

1. Open the app and change model to the GPT-4 Vision Preview.
2. Input a prompt and image in the field.
3. Click on the "Send" button to see the preview.

### Expected Behavior

The GPT-4 Vision Preview should display the full result message, without cutting it off or truncating it.

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by H0llyW00dzZ** [comment]
> ### Bug Description
> I'm writing to report a bug I've encountered while using the GPT-4 Vision Preview feature in the app. The feature is cutting off the result message, showing only a single line, and not displaying the full message.
> 
> ### Steps to Reproduce
> 1. Open the app and change model to the GPT-4 Vision Preview.
> 2. Input a prompt and image in the field.
> 3. Click on the "Send" button to see the preview.
> 
> ### Expected Behavior
> The GPT-4 Vision Preview should display the full result message, without cutting it off or truncating it.
> 
> ### Screenshots
> _No response_
> 
> ### Deployment Method
> * [ ]  Docker
> * [x]  Vercel
> * [ ]  Server
> 
> ### Desktop OS
> _No response_
> 
> ### Desktop Browser
> _No response_
> 
> ### Desktop Browser Version
> _No response_
> 
> ### Smartphone Device
> _No response_
> 
> ### Smartphone OS
> _No response_
> 
> ### Smartphone Browser
> _No response_
> 
> ### Smartphone Browser Version
> _No response_
> 
> ### Additional Logs
> _No response_

You have to enabled this manually.

![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/17626300/8098009e-b409-4ca7-8e12-8d6b58cd844b)

**Comment by H0llyW00dzZ** [comment]
For instance, in a specific chat, you can set the max tokens instead of doing so in the settings, because that will apply it as a global setting.

![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/17626300/aef2404b-8901-4269-af31-55faa3ad1f90)
