### ISSUE TITLE
[Bug] CF部署，正常设置环境变量报错

### ISSUE THREAD

**Issue by yunxilyf** [H0llyW00dzZ/ChatGPT-Next-Web#91]
**Describe the bug**

**To Reproduce**
报错内容如下，环境变量设置了BASE_URL 、OPENAI_API_KEY这两个，直接进去提问报错，手动在设置里面设置BASE_URL和key没有报错出现，只有设置环境变量的时候会出现，且Vercel部署没有这个问题
{
  "error": true,
  "msg": "Access Forbidden"
}

**Deployment**
cloudflare

**Desktop (please complete the following information):**
 Browser

**Comment by H0llyW00dzZ** [comment]
oh wait I forgot to disable a cors

**Comment by H0llyW00dzZ** [comment]
Check https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/actions/runs/6849288188/job/18621166193
