### ISSUE TITLE
[Bug] 使用dall-e-3模型时图片渲染问题

### ISSUE THREAD

**Issue by yunxilyf** [H0llyW00dzZ/ChatGPT-Next-Web#97]
**Describe the bug**

**To Reproduce**
图片渲染错误
![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/44936564/9772958c-53dd-482f-9117-efa4ed3a93a3)

**Deployment**
 Vercel

**Desktop (please complete the following information):**
chrome

**Smartphone (please complete the following information):**
- Browser

**Comment by H0llyW00dzZ** [comment]
that's session expired after a few hours (average 2 hours) when image is already generated, haven't implement it yet for save a image to local

**Comment by yunxilyf** [comment]
![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/44936564/5a5a11e1-8554-4d42-93d5-eb71f0dfd025)
Normal rendering should look like this:

**Comment by yunxilyf** [comment]
![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/44936564/25e7bdb1-b0ea-4e64-ab42-d578e84c8702)
![image](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/assets/44936564/09eac4d5-069b-4ce4-bb8e-eac73f6fe748)
The above is the content of normal rendering, and the following is the content of default output, so this bug needs to be fixed.

**Comment by H0llyW00dzZ** [comment]
Fix H0llyW00dzZ#97 DALL·E Models #98
